// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ThAmCo.Catering.Data.Migrations
{
    [DbContext(typeof(CateringDbContext))]
    partial class CateringDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("FoodBookingMenu", b =>
                {
                    b.Property<int>("FoodBookingsFoodBookingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FoodBookingsFoodBookingId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("FoodBookingMenu");
                });

            modelBuilder.Entity("FoodItemMenuFoodItem", b =>
                {
                    b.Property<int>("FoodItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuFoodItemsMenuFoodItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FoodItemId", "MenuFoodItemsMenuFoodItemId");

                    b.HasIndex("MenuFoodItemsMenuFoodItemId");

                    b.ToTable("FoodItemMenuFoodItem");
                });

            modelBuilder.Entity("MenuMenuFoodItem", b =>
                {
                    b.Property<int>("MenuFoodItemsMenuFoodItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MenuFoodItemsMenuFoodItemId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("MenuMenuFoodItem");
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.FoodBooking", b =>
                {
                    b.Property<int>("FoodBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("INTEGER");

                    b.HasKey("FoodBookingId");

                    b.ToTable("FoodBookings");
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.FoodItem", b =>
                {
                    b.Property<int>("FoodItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<float>("UnitPrice")
                        .HasColumnType("REAL");

                    b.HasKey("FoodItemId");

                    b.ToTable("FoodItems");
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("MenuId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.MenuFoodItem", b =>
                {
                    b.Property<int>("MenuFoodItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MenuFoodItemId");

                    b.HasIndex("FoodItemId")
                        .IsUnique();

                    b.ToTable("MenuFoodItems");
                });

            modelBuilder.Entity("FoodBookingMenu", b =>
                {
                    b.HasOne("ThAmCo.Catering.Data.FoodBooking", null)
                        .WithMany()
                        .HasForeignKey("FoodBookingsFoodBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThAmCo.Catering.Data.Menu", null)
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoodItemMenuFoodItem", b =>
                {
                    b.HasOne("ThAmCo.Catering.Data.FoodItem", null)
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThAmCo.Catering.Data.MenuFoodItem", null)
                        .WithMany()
                        .HasForeignKey("MenuFoodItemsMenuFoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MenuMenuFoodItem", b =>
                {
                    b.HasOne("ThAmCo.Catering.Data.MenuFoodItem", null)
                        .WithMany()
                        .HasForeignKey("MenuFoodItemsMenuFoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThAmCo.Catering.Data.Menu", null)
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.Menu", b =>
                {
                    b.HasOne("ThAmCo.Catering.Data.FoodBooking", null)
                        .WithOne()
                        .HasForeignKey("ThAmCo.Catering.Data.Menu", "MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThAmCo.Catering.Data.MenuFoodItem", null)
                        .WithOne()
                        .HasForeignKey("ThAmCo.Catering.Data.Menu", "MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.MenuFoodItem", b =>
                {
                    b.HasOne("ThAmCo.Catering.Data.FoodItem", null)
                        .WithOne()
                        .HasForeignKey("ThAmCo.Catering.Data.MenuFoodItem", "FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
