// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThAmCo.Events.Data;

#nullable disable

namespace ThAmCo.Events.Data.Migrations
{
    [DbContext(typeof(EventsDbContext))]
    [Migration("20241107154812_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ThAmCo.Events.Data.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventTypeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FoodBookingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReservationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("ThAmCo.Events.Data.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GuestId");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("ThAmCo.Events.Data.GuestBooking", b =>
                {
                    b.Property<int>("GuestBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuestBookingId");

                    b.HasIndex("EventId");

                    b.HasIndex("GuestId");

                    b.ToTable("GuestBookings");
                });

            modelBuilder.Entity("ThAmCo.Events.Data.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StaffId");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            StaffId = 1,
                            FirstName = "FirstName1",
                            LastName = "LastName1",
                            Role = "Manager"
                        },
                        new
                        {
                            StaffId = 2,
                            FirstName = "FirstName2",
                            LastName = "LastName2",
                            Role = "Chef"
                        },
                        new
                        {
                            StaffId = 3,
                            FirstName = "FirstName3",
                            LastName = "LastName3",
                            Role = "Bartender"
                        },
                        new
                        {
                            StaffId = 4,
                            FirstName = "FirstName4",
                            LastName = "LastName4",
                            Role = "Security"
                        },
                        new
                        {
                            StaffId = 5,
                            FirstName = "FirstName5",
                            LastName = "LastName5",
                            Role = "Coordinator"
                        },
                        new
                        {
                            StaffId = 6,
                            FirstName = "FirstName6",
                            LastName = "LastName6",
                            Role = "Event Planner"
                        },
                        new
                        {
                            StaffId = 7,
                            FirstName = "FirstName7",
                            LastName = "LastName7",
                            Role = "Cleaner"
                        },
                        new
                        {
                            StaffId = 8,
                            FirstName = "FirstName8",
                            LastName = "LastName8",
                            Role = "Technician"
                        },
                        new
                        {
                            StaffId = 9,
                            FirstName = "FirstName9",
                            LastName = "LastName9",
                            Role = "DJ"
                        },
                        new
                        {
                            StaffId = 10,
                            FirstName = "FirstName10",
                            LastName = "LastName10",
                            Role = "Photographer"
                        },
                        new
                        {
                            StaffId = 11,
                            FirstName = "FirstName11",
                            LastName = "LastName11",
                            Role = "Logistics Manager"
                        },
                        new
                        {
                            StaffId = 12,
                            FirstName = "FirstName12",
                            LastName = "LastName12",
                            Role = "Driver"
                        },
                        new
                        {
                            StaffId = 13,
                            FirstName = "FirstName13",
                            LastName = "LastName13",
                            Role = "Greeter"
                        },
                        new
                        {
                            StaffId = 14,
                            FirstName = "FirstName14",
                            LastName = "LastName14",
                            Role = "Marketing Specialist"
                        },
                        new
                        {
                            StaffId = 15,
                            FirstName = "FirstName15",
                            LastName = "LastName15",
                            Role = "Ticketing Agent"
                        },
                        new
                        {
                            StaffId = 16,
                            FirstName = "FirstName16",
                            LastName = "LastName16",
                            Role = "Host"
                        },
                        new
                        {
                            StaffId = 17,
                            FirstName = "FirstName17",
                            LastName = "LastName17",
                            Role = "VIP Assistant"
                        },
                        new
                        {
                            StaffId = 18,
                            FirstName = "FirstName18",
                            LastName = "LastName18",
                            Role = "Customer Support"
                        },
                        new
                        {
                            StaffId = 19,
                            FirstName = "FirstName19",
                            LastName = "LastName19",
                            Role = "Videographer"
                        },
                        new
                        {
                            StaffId = 20,
                            FirstName = "FirstName20",
                            LastName = "LastName20",
                            Role = "Stage Hand"
                        },
                        new
                        {
                            StaffId = 21,
                            FirstName = "FirstName21",
                            LastName = "LastName21",
                            Role = "Waiter"
                        },
                        new
                        {
                            StaffId = 22,
                            FirstName = "FirstName22",
                            LastName = "LastName22",
                            Role = "Manager"
                        },
                        new
                        {
                            StaffId = 23,
                            FirstName = "FirstName23",
                            LastName = "LastName23",
                            Role = "Chef"
                        },
                        new
                        {
                            StaffId = 24,
                            FirstName = "FirstName24",
                            LastName = "LastName24",
                            Role = "Bartender"
                        },
                        new
                        {
                            StaffId = 25,
                            FirstName = "FirstName25",
                            LastName = "LastName25",
                            Role = "Security"
                        },
                        new
                        {
                            StaffId = 26,
                            FirstName = "FirstName26",
                            LastName = "LastName26",
                            Role = "Coordinator"
                        },
                        new
                        {
                            StaffId = 27,
                            FirstName = "FirstName27",
                            LastName = "LastName27",
                            Role = "Event Planner"
                        },
                        new
                        {
                            StaffId = 28,
                            FirstName = "FirstName28",
                            LastName = "LastName28",
                            Role = "Cleaner"
                        },
                        new
                        {
                            StaffId = 29,
                            FirstName = "FirstName29",
                            LastName = "LastName29",
                            Role = "Technician"
                        },
                        new
                        {
                            StaffId = 30,
                            FirstName = "FirstName30",
                            LastName = "LastName30",
                            Role = "DJ"
                        },
                        new
                        {
                            StaffId = 31,
                            FirstName = "FirstName31",
                            LastName = "LastName31",
                            Role = "Photographer"
                        },
                        new
                        {
                            StaffId = 32,
                            FirstName = "FirstName32",
                            LastName = "LastName32",
                            Role = "Logistics Manager"
                        },
                        new
                        {
                            StaffId = 33,
                            FirstName = "FirstName33",
                            LastName = "LastName33",
                            Role = "Driver"
                        },
                        new
                        {
                            StaffId = 34,
                            FirstName = "FirstName34",
                            LastName = "LastName34",
                            Role = "Greeter"
                        },
                        new
                        {
                            StaffId = 35,
                            FirstName = "FirstName35",
                            LastName = "LastName35",
                            Role = "Marketing Specialist"
                        },
                        new
                        {
                            StaffId = 36,
                            FirstName = "FirstName36",
                            LastName = "LastName36",
                            Role = "Ticketing Agent"
                        },
                        new
                        {
                            StaffId = 37,
                            FirstName = "FirstName37",
                            LastName = "LastName37",
                            Role = "Host"
                        },
                        new
                        {
                            StaffId = 38,
                            FirstName = "FirstName38",
                            LastName = "LastName38",
                            Role = "VIP Assistant"
                        },
                        new
                        {
                            StaffId = 39,
                            FirstName = "FirstName39",
                            LastName = "LastName39",
                            Role = "Customer Support"
                        },
                        new
                        {
                            StaffId = 40,
                            FirstName = "FirstName40",
                            LastName = "LastName40",
                            Role = "Videographer"
                        },
                        new
                        {
                            StaffId = 41,
                            FirstName = "FirstName41",
                            LastName = "LastName41",
                            Role = "Stage Hand"
                        },
                        new
                        {
                            StaffId = 42,
                            FirstName = "FirstName42",
                            LastName = "LastName42",
                            Role = "Waiter"
                        },
                        new
                        {
                            StaffId = 43,
                            FirstName = "FirstName43",
                            LastName = "LastName43",
                            Role = "Manager"
                        },
                        new
                        {
                            StaffId = 44,
                            FirstName = "FirstName44",
                            LastName = "LastName44",
                            Role = "Chef"
                        },
                        new
                        {
                            StaffId = 45,
                            FirstName = "FirstName45",
                            LastName = "LastName45",
                            Role = "Bartender"
                        },
                        new
                        {
                            StaffId = 46,
                            FirstName = "FirstName46",
                            LastName = "LastName46",
                            Role = "Security"
                        },
                        new
                        {
                            StaffId = 47,
                            FirstName = "FirstName47",
                            LastName = "LastName47",
                            Role = "Coordinator"
                        },
                        new
                        {
                            StaffId = 48,
                            FirstName = "FirstName48",
                            LastName = "LastName48",
                            Role = "Event Planner"
                        },
                        new
                        {
                            StaffId = 49,
                            FirstName = "FirstName49",
                            LastName = "LastName49",
                            Role = "Cleaner"
                        },
                        new
                        {
                            StaffId = 50,
                            FirstName = "FirstName50",
                            LastName = "LastName50",
                            Role = "Technician"
                        });
                });

            modelBuilder.Entity("ThAmCo.Events.Data.Staffing", b =>
                {
                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StaffId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("Staffing");
                });

            modelBuilder.Entity("ThAmCo.Events.Data.GuestBooking", b =>
                {
                    b.HasOne("ThAmCo.Events.Data.Event", null)
                        .WithMany("GuestBookings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThAmCo.Events.Data.Guest", null)
                        .WithMany("GuestBookings")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ThAmCo.Events.Data.Staffing", b =>
                {
                    b.HasOne("ThAmCo.Events.Data.Event", null)
                        .WithMany("Staffings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThAmCo.Events.Data.Staff", null)
                        .WithMany("Staffings")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ThAmCo.Events.Data.Event", b =>
                {
                    b.Navigation("GuestBookings");

                    b.Navigation("Staffings");
                });

            modelBuilder.Entity("ThAmCo.Events.Data.Guest", b =>
                {
                    b.Navigation("GuestBookings");
                });

            modelBuilder.Entity("ThAmCo.Events.Data.Staff", b =>
                {
                    b.Navigation("Staffings");
                });
#pragma warning restore 612, 618
        }
    }
}
