// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThAmCo.Events.Data;

#nullable disable

namespace ThAmCo.Events.Data.Migrations
{
    [DbContext(typeof(EventsDbContext))]
    partial class EventsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThAmCo.Events.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FoodBookingId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReservationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("ThAmCo.Events.Models.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuestId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAnonymised")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GuestId");

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            GuestId = 1,
                            Email = "alice.green@example.com",
                            FirstName = "Alice",
                            IsAnonymised = false,
                            LastName = "Green"
                        },
                        new
                        {
                            GuestId = 2,
                            Email = "bob.smith@example.com",
                            FirstName = "Bob",
                            IsAnonymised = false,
                            LastName = "Smith"
                        },
                        new
                        {
                            GuestId = 3,
                            Email = "carol.johnson@example.com",
                            FirstName = "Carol",
                            IsAnonymised = false,
                            LastName = "Johnson"
                        },
                        new
                        {
                            GuestId = 4,
                            Email = "david.brown@example.com",
                            FirstName = "David",
                            IsAnonymised = false,
                            LastName = "Brown"
                        },
                        new
                        {
                            GuestId = 5,
                            Email = "ella.davis@example.com",
                            FirstName = "Ella",
                            IsAnonymised = false,
                            LastName = "Davis"
                        },
                        new
                        {
                            GuestId = 6,
                            Email = "frank.wilson@example.com",
                            FirstName = "Frank",
                            IsAnonymised = false,
                            LastName = "Wilson"
                        },
                        new
                        {
                            GuestId = 7,
                            Email = "grace.martinez@example.com",
                            FirstName = "Grace",
                            IsAnonymised = false,
                            LastName = "Martinez"
                        },
                        new
                        {
                            GuestId = 8,
                            Email = "henry.anderson@example.com",
                            FirstName = "Henry",
                            IsAnonymised = false,
                            LastName = "Anderson"
                        },
                        new
                        {
                            GuestId = 9,
                            Email = "ivy.thomas@example.com",
                            FirstName = "Ivy",
                            IsAnonymised = false,
                            LastName = "Thomas"
                        },
                        new
                        {
                            GuestId = 10,
                            Email = "jack.moore@example.com",
                            FirstName = "Jack",
                            IsAnonymised = false,
                            LastName = "Moore"
                        },
                        new
                        {
                            GuestId = 11,
                            Email = "olivia.miller@example.com",
                            FirstName = "Olivia",
                            IsAnonymised = false,
                            LastName = "Miller"
                        },
                        new
                        {
                            GuestId = 12,
                            Email = "william.garcia@example.com",
                            FirstName = "William",
                            IsAnonymised = false,
                            LastName = "Garcia"
                        },
                        new
                        {
                            GuestId = 13,
                            Email = "noah.rodriguez@example.com",
                            FirstName = "Noah",
                            IsAnonymised = false,
                            LastName = "Rodriguez"
                        },
                        new
                        {
                            GuestId = 14,
                            Email = "sophia.lee@example.com",
                            FirstName = "Sophia",
                            IsAnonymised = false,
                            LastName = "Lee"
                        },
                        new
                        {
                            GuestId = 15,
                            Email = "jacob.nguyen@example.com",
                            FirstName = "Jacob",
                            IsAnonymised = false,
                            LastName = "Nguyen"
                        },
                        new
                        {
                            GuestId = 16,
                            Email = "emma.clark@example.com",
                            FirstName = "Emma",
                            IsAnonymised = false,
                            LastName = "Clark"
                        },
                        new
                        {
                            GuestId = 17,
                            Email = "ethan.hall@example.com",
                            FirstName = "Ethan",
                            IsAnonymised = false,
                            LastName = "Hall"
                        },
                        new
                        {
                            GuestId = 18,
                            Email = "ava.walker@example.com",
                            FirstName = "Ava",
                            IsAnonymised = false,
                            LastName = "Walker"
                        },
                        new
                        {
                            GuestId = 19,
                            Email = "liam.harris@example.com",
                            FirstName = "Liam",
                            IsAnonymised = false,
                            LastName = "Harris"
                        },
                        new
                        {
                            GuestId = 20,
                            Email = "isabella.wright@example.com",
                            FirstName = "Isabella",
                            IsAnonymised = false,
                            LastName = "Wright"
                        });
                });

            modelBuilder.Entity("ThAmCo.Events.Models.GuestBooking", b =>
                {
                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("DidAttend")
                        .HasColumnType("bit");

                    b.HasKey("GuestId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("GuestBookings");
                });

            modelBuilder.Entity("ThAmCo.Events.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAnonymised")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFirstAider")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffId");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            StaffId = 1,
                            FirstName = "John",
                            IsAnonymised = false,
                            IsFirstAider = false,
                            LastName = "Doe",
                            Role = "Chef"
                        },
                        new
                        {
                            StaffId = 2,
                            FirstName = "Jane",
                            IsAnonymised = false,
                            IsFirstAider = false,
                            LastName = "Smith",
                            Role = "Server"
                        },
                        new
                        {
                            StaffId = 3,
                            FirstName = "Emily",
                            IsAnonymised = false,
                            IsFirstAider = true,
                            LastName = "Johnson",
                            Role = "Manager"
                        },
                        new
                        {
                            StaffId = 4,
                            FirstName = "Michael",
                            IsAnonymised = false,
                            IsFirstAider = true,
                            LastName = "Williams",
                            Role = "Chef"
                        },
                        new
                        {
                            StaffId = 5,
                            FirstName = "Sarah",
                            IsAnonymised = false,
                            IsFirstAider = true,
                            LastName = "Brown",
                            Role = "Server"
                        },
                        new
                        {
                            StaffId = 6,
                            FirstName = "David",
                            IsAnonymised = false,
                            IsFirstAider = false,
                            LastName = "Jones",
                            Role = "Bartender"
                        },
                        new
                        {
                            StaffId = 7,
                            FirstName = "Laura",
                            IsAnonymised = false,
                            IsFirstAider = false,
                            LastName = "Garcia",
                            Role = "Host"
                        },
                        new
                        {
                            StaffId = 8,
                            FirstName = "Daniel",
                            IsAnonymised = false,
                            IsFirstAider = true,
                            LastName = "Martinez",
                            Role = "Sous Chef"
                        },
                        new
                        {
                            StaffId = 9,
                            FirstName = "Sophia",
                            IsAnonymised = false,
                            IsFirstAider = true,
                            LastName = "Anderson",
                            Role = "Server"
                        },
                        new
                        {
                            StaffId = 10,
                            FirstName = "James",
                            IsAnonymised = false,
                            IsFirstAider = true,
                            LastName = "Taylor",
                            Role = "Manager"
                        },
                        new
                        {
                            StaffId = 11,
                            FirstName = "Olivia",
                            IsAnonymised = false,
                            IsFirstAider = false,
                            LastName = "Nelson",
                            Role = "Chef"
                        },
                        new
                        {
                            StaffId = 12,
                            FirstName = "William",
                            IsAnonymised = false,
                            IsFirstAider = true,
                            LastName = "Perez",
                            Role = "Server"
                        },
                        new
                        {
                            StaffId = 13,
                            FirstName = "Abigail",
                            IsAnonymised = false,
                            IsFirstAider = true,
                            LastName = "Campbell",
                            Role = "Manager"
                        },
                        new
                        {
                            StaffId = 14,
                            FirstName = "Ethan",
                            IsAnonymised = false,
                            IsFirstAider = false,
                            LastName = "Parker",
                            Role = "Chef"
                        },
                        new
                        {
                            StaffId = 15,
                            FirstName = "Sophia",
                            IsAnonymised = false,
                            IsFirstAider = true,
                            LastName = "Evans",
                            Role = "Server"
                        },
                        new
                        {
                            StaffId = 16,
                            FirstName = "Mason",
                            IsAnonymised = false,
                            IsFirstAider = false,
                            LastName = "Edwards",
                            Role = "Bartender"
                        },
                        new
                        {
                            StaffId = 17,
                            FirstName = "Ava",
                            IsAnonymised = false,
                            IsFirstAider = true,
                            LastName = "Collins",
                            Role = "Host"
                        },
                        new
                        {
                            StaffId = 18,
                            FirstName = "Jacob",
                            IsAnonymised = false,
                            IsFirstAider = false,
                            LastName = "Stewart",
                            Role = "Sous Chef"
                        },
                        new
                        {
                            StaffId = 19,
                            FirstName = "Emily",
                            IsAnonymised = false,
                            IsFirstAider = true,
                            LastName = "Sanchez",
                            Role = "Server"
                        },
                        new
                        {
                            StaffId = 20,
                            FirstName = "Michael",
                            IsAnonymised = false,
                            IsFirstAider = true,
                            LastName = "Morris",
                            Role = "Manager"
                        });
                });

            modelBuilder.Entity("ThAmCo.Events.Models.Staffing", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<bool>("DidAttend")
                        .HasColumnType("bit");

                    b.HasKey("EventId", "StaffId");

                    b.HasIndex("StaffId");

                    b.ToTable("Staffing");
                });

            modelBuilder.Entity("ThAmCo.Events.Models.GuestBooking", b =>
                {
                    b.HasOne("ThAmCo.Events.Models.Event", "Event")
                        .WithMany("GuestBookings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThAmCo.Events.Models.Guest", "Guest")
                        .WithMany("GuestBookings")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("ThAmCo.Events.Models.Staffing", b =>
                {
                    b.HasOne("ThAmCo.Events.Models.Event", "Event")
                        .WithMany("Staffings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThAmCo.Events.Models.Staff", "Staff")
                        .WithMany("Staffings")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("ThAmCo.Events.Models.Event", b =>
                {
                    b.Navigation("GuestBookings");

                    b.Navigation("Staffings");
                });

            modelBuilder.Entity("ThAmCo.Events.Models.Guest", b =>
                {
                    b.Navigation("GuestBookings");
                });

            modelBuilder.Entity("ThAmCo.Events.Models.Staff", b =>
                {
                    b.Navigation("Staffings");
                });
#pragma warning restore 612, 618
        }
    }
}
